[build]
builder = "NIXPACKS"
buildCommand = """
set -e
npm install && \
apt-get update -y && \
apt-get install -y python3.10 python3.10-venv python3.10-distutils build-essential gfortran libatlas-base-dev curl && \
cd hestia-sim && \
python3.10 -m venv .venv && \
. .venv/bin/activate && \
pip install --upgrade pip && \
pip install \
pandas==2.2.2 \
numpy==2.1.1 \
simpy==4.1.1 \
simple-term-menu==1.6.4 \
matplotlib==3.9.2 \
seaborn==0.13.2 \
scipy==1.14.1 \
networkx==3.4.2 \
matplotlib-inline==0.1.7 \
notebook==7.3.1 \
xlsxwriter==3.2.0
"""

[start]
cmd = "npm start"
