[build]
builder = "NIXPACKS"
buildCommand = """
npm install && \
apt-get update -y && \
apt-get install -y python3 python3-venv && \
cd hestia-sim && \
python3 -m venv .venv && \
. .venv/bin/activate && \
pip install --no-cache-dir -r requirements.txt
"""

[start]
cmd = "npm start"
