[build]
builder = "NIXPACKS"
buildCommand = """
npm install && \
apt-get update -y && \
apt-get install -y python3 python3-pip python3-venv && \
cd hestia-sim && \
pip install --no-cache-dir -r requirements.txt
"""

[start]
cmd = "npm start"
