[build]
builder = "NIXPACKS"
buildCommand = """
npm install && \
apt-get update -y && \
apt-get install -y python3 python3-pip python3-venv curl && \
curl -sSL https://install.python-poetry.org | python3 - && \
export PATH="/root/.local/bin:$PATH" && \
cd hestia-sim && \
/root/.local/bin/poetry install
"""

[start]
cmd = "npm start"
