[build]
builder = "NIXPACKS"
buildCommand = """
npm install && \
apt-get update -y && \
apt-get install -y python3 curl && \
curl -sS https://bootstrap.pypa.io/get-pip.py | python3 && \
cd hestia-sim && \
python3 -m pip install --no-cache-dir -r requirements.txt
"""

[start]
cmd = "npm start"
